create table endoscopist (
    endoscopist_id serial,
    action_on timestamp without time zone DEFAULT ('now'::text)::timestamp not null,
    action_by character varying DEFAULT current_user not null,
    record_comment character varying,
    inserted_on date DEFAULT ('now'::text)::date,
    inserted_by character varying default current_user,
    endo_initials character varying,
    endo_first_name character varying,
    endo_middle_name character varying,
    endo_last_name character varying,
    endo_name_suffix character varying,
    endo_degree character varying,
    salutation character varying,
    mail_name character varying,
    endo_organization character varying,
    endo_address1 character varying,
    endo_address2 character varying,
    endo_address3 character varying,
    endo_city character varying,
    endo_state character varying,
    endo_zip character varying,
    endo_direct_phone character varying,
    endo_pager character varying,
    endo_other_phone character varying,
    endo_email character varying,
    endo_dob date,
    endo_gender_male smallint,
    endo_specialty character varying,
    endo_med_grad_year character varying,
    endo_fellowship smallint,
    endo_fellow_grad_year character varying,
    endo_fellow_discipline character varying,
    year_first_colo character varying,
    comments text,
    participating smallint,
    main_site character varying,
    report_handling character varying,
    enroll_survey_done smallint,
    steering_committee smallint,
    endo_status character varying,
    endo_status_date date,
    endo_pseudo_name smallint,
    constraint endoscopist_pkey PRIMARY KEY (endoscopist_id)
    );
grant all on endoscopist to nhcr2_rc, nhcr2_staff;