create table endoscopist (
    endoscopist_id serial,
    action_on timestamp without time zone not null,
    action_by character varying not null,
    record_comment character varying,
    inserted_on date DEFAULT ('now'::text)::date,
    inserted_by character varying,
    endo_initials character varying,
    endo_first_name character varying,
    endo_middle_name character varying,
    endo_last_name character varying,
    endo_name_suffix character varying,
    endo_degree character varying,
    salutation character varying,
    mail_name character varying,
    endo_organization character varying,
    endo_address1 character varying,
    endo_address2 character varying,
    endo_address3 character varying,
    endo_city character varying,
    endo_state character varying,
    endo_zip smallint,
    endo_direct_phone character varying,
    endo_pager character varying,
    endo_other_phone character varying,
    endo_email character varying,
    endo_reach_sun smallint,
    endo_reach_mon smallint,
    endo_reach_tues smallint,
    endo_reach_wed smallint,
    endo_reach_thurs smallint,
    endo_reach_fri smallint,
    endo_reach_sat smallint,
    endo_dob date,
    endo_gender_male smallint,
    endo_specialty character varying,
    endo_med_grad_year smallint,
    endo_res_grad_year smallint,
    endo_res_location character varying,
    endo_fellowship smallint,
    endo_fellow_grad_year smallint,
    endo_fellow_location character varying,
    endo_fellow_discipline character varying,
    year_first_colo smallint,
    year_first_colo_here smallint,
    comments text,
    report_group_code smallint,
    report_group_lead smallint,
    participating smallint,
    main_site character varying,
    report_handling smallint,
    enroll_survey_done smallint,
    steering_committee smallint,
    endo_status character varying,
    endo_status_date date,
    endo_pseudo_name smallint,
    endo_reach_start_time time without time zone,
    endo_reach_end_time time without time zone,
    constraint endoscopist_pkey PRIMARY KEY (endoscopist_id)
    );
