create table CREATE TABLE facility(
    facility_id varchar,
    action_on timestamp without time zone not null,
    action_by varchar not null,
    record_comment varchar,
    inserted_on date DEFAULT ('now'::text)::date,
    inserted_by varchar,
    facility_name varchar,
    facility_pseudo_name varchar,
    address1 varchar,
    address2 varchar,
    address3 varchar,
    city varchar,
    state varchar,
    zip varchar,
    fax varchar,
    status varchar,
    status_date date,
    facility_type varchar,
    ctc smallint,
    how_write_reports varchar,
    comments varchar,
    contact1_name varchar,
    contact1_phone varchar,
    contact1_email varchar,
    contact1_type varchar,
    contact2_name varchar,
    contact2_phone varchar,
    contact2_email varchar,
    contact2_type varchar,
    contact3_name varchar,
    contact3_phone varchar,
    contact3_email varchar,
    contact3_type varchar,
    facility_type smallint,
    contact_reports_name varchar,
    contact_reports_phone varchar,
    contact_reports_email varchar,
    reports_notes smallint,
    reports_instructions text,
    pth_consent_form_reqd smallint,
    pth_req_sort_col varchar,
    pth_req_notes varchar,
    pth_req_instructions text,
    facility_pseudo_name smallint,
    sort_pth_req_endo smallint,
    pth_req_required smallint,
    constraint facility_pkey PRIMARY KEY (facility_id)
)
