create table import_scanned_surv_data (
    id serial,
    action_on timestamp without time zone not null,
    action_by character varying not null,
    record_comment character varying,
    inserted_on date DEFAULT ('now'::text)::date,
    inserted_by character varying,
    time_stamp character varying,
    verify_ws character varying,
    form_id character varying,
    batch_num bigint,
    batch_dir character varying,
    bat_pg_no integer,
    bat_pg_cnt integer,
    barcode character varying,
    ex_rtn_scrn character varying,
    ex_phx_plp character varying,
    ex_phx_cca character varying,
    ex_fhx_plp character varying,
    ex_phc_crohn character varying,
    ex_fhx_cca character varying,
    ex_sympt character varying,
    ex_phx_uc character varying,
    ex_oth character varying,
    uc_age_dx integer,
    crohn_age_dx integer,
    prep_typ character varying,
    prev_colo character varying,
    pcr_allneg character varying,
    pcr_polyp character varying,
    pcr_cca character varying,
    pcr_roids character varying,
    pcr_dvt character varying,
    pcr_oth character varying,
    pcr_rectalca character varying,
    ps_allneg character varying,
    ps_polyp character varying,
    ps_cca character varying,
    ps_roids character varying,
    ps_dvt character varying,
    ps_oth character varying,
    ps_rectalca character varying,
    not_used boolean,
    ca_mom character varying,
    ca_dad character varying,
    ca_sis character varying,
    ca_bro character varying,
    ca_kid character varying,
    rb450_bro character varying,
    rb450_mom character varying,
    rb450_dk character varying,
    rb450_sis character varying,
    rb450_dad character varying,
    rb450_kid character varying,
    rgt50_bro character varying,
    rgt50_mom character varying,
    rgt50_dk character varying,
    rgt50_sis character varying,
    rgt50_dad character varying,
    rgt50_child character varying,
    colon_plp character varying,
    fam_colon_plp character varying,
    fap character varying,
    lynch_synd character varying,
    ibs character varying,
    oth_ca character varying,
    oth_ca_fam character varying,
    aspirin character varying,
    asp_duration character varying,
    coumadin character varying,
    vitamins character varying,
    otc_anti_infl character varying,
    otc_ai_duration character varying,
    health character varying,
    smokev character varying,
    smokyrs integer,
    smoknum character varying,
    alconum character varying,
    exercise character varying,
    height_ft integer,
    height_in integer,
    weight_now integer,
    weight_20 integer,
    ins_mcare character varying,
    ins_mcaid character varying,
    ins_priv character varying,
    ins_hmo character varying,
    ins_unsure character varying,
    ins_none character varying,
    ins_oth character varying,
    hispanic character varying,
    race_white character varying,
    race_black character varying,
    race_asain character varying,
    race_pac_isl character varying,
    race_amind character varying,
    race_oth character varying,
    education character varying,
    marital_status character varying,
    birth_state character varying,
    foriegn_born character varying,
    not_used1 boolean,
    not_used2 boolean,
    not_used3 boolean,
    not_used4 boolean,
    not_used5 boolean,
    not_used6 boolean,
    not_used7 boolean,
    not_used8 boolean,
    not_used9 boolean,
    not_used10 boolean,
    not_used11 boolean,
    not_used12 boolean,
    not_used13 boolean,
    not_used14 boolean,
    not_used15 boolean,
    not_used16 boolean,
    not_used17 boolean,
    not_used18 boolean,
    not_used19 boolean,
    not_used20 boolean,
    not_used21 boolean,
    not_used22 boolean,
    not_used23 boolean,
    person_id bigint,
    dead boolean,
    refused boolean,
    gender character varying,
    facility_id character varying,
    endo_code integer,
    rpt_grp character varying,
    added_to_survey boolean,
    event_id bigint,
    event_date date,
    cprs_batch_id bigint,
    constraint forms_pkey PRIMARY KEY (id)
);
ALTER TABLE import_scanned_surv_data
    OWNER TO informatics;
GRANT ALL ON TABLE import_scanned_surv_data TO informatics;