create table path_lab (
    path_lab_id serial,
    action_on timestamp without time zone,
    action_by varchar,
    record_comment varchar,
    inserted_on date DEFAULT ('now'::text)::date,
    inserted_by varchar,
    lab_name varchar,
    lab_code varchar,
    contact1_name varchar,
    contact1_phone varchar,
    contact1_email varchar,
    contact1_type varchar,
    contact2_name varchar,
    contact2_phone varchar,
    contact2_email varchar,
    contact2_type varchar,
    address1 varchar,
    address2 varchar,
    city varchar,
    state varchar(2),
    zip varchar,
    request_procedure text,
    notes smallint,
    status varchar,
    path_report_trigger smallint,
    sort_path_requests_by varchar,
    constraint path_lab_pkey primary key (path_lab_id)
)