create table facility(
    id serial not null,
    action_on timestamp without time zone DEFAULT now(),
    action_by character varying DEFAULT "current_user"(),
    record_comment character varying,
    inserted_on date DEFAULT ('now'::text)::date,
    inserted_by character varying DEFAULT "current_user"(),
    facility_id varchar,
    facility_name varchar,
    facility_pseudo_name varchar,
    address1 varchar,
    address2 varchar,
    address3 varchar,
    city varchar,
    state varchar,
    zip varchar,
    fax varchar,
    status varchar,
    status_date date,
    implementation_date date,
    facility_type varchar,
    how_write_reports varchar,
    comments varchar,
    contact1_name varchar,
    contact1_phone varchar,
    contact1_email varchar,
    contact1_type varchar,
    contact2_name varchar,
    contact2_phone varchar,
    contact2_email varchar,
    contact2_type varchar,
    contact3_name varchar,
    contact3_phone varchar,
    contact3_email varchar,
    contact3_type varchar,
    pth_reports_contact_name varchar,
    pth_reports_contact_phone varchar,
    pth_reports_contact_email varchar,
    pth_req_required smallint,
    pth_consent_form_reqd smallint,
    pth_req_sort_col varchar,
    pth_req_instructions text,
    irb_of_record varchar,
    irb_review_date date,
    irb_consent_form varchar,
    irb_active_consent_version varchar,
    irb_approval_date date,
    irb_expiration_date date,
    irb_contact_name varchar,
    irb_contact_phone varchar,
    irb_contact_email varchar,
    constraint facility_pkey PRIMARY KEY (facility_id)
)
grant select on facility to NHCR2_rc;