create table findings
(
    id serial not null,
    action_on timestamp without time zone,
    action_by varchar,
    record_comment varchar,
    inserted_on date DEFAULT ('now'::text)::date,
    inserted_by varchar,
    colo_id integer,
    event_id bigint,
    event_type varchar,
    path_report_complete integer,
    dob date,
    exam_date date,
    endoscopist_id integer,
    facility_id varchar,
    facility_type varchar,
    gender_calcd varchar,
    end_proc_stat_rr varchar,
    prep varchar,
    myDx varchar,
    adenoma_detected integer,
    clinically_serrated integer,
    proximal_serrated integer,
    screening integer,
    surveillance integer,
    diagnostic integer,
    eligible integer,
    indication_calculated varchar,
    ind_scr_nosym varchar,
    ind_scr_fhxcc varchar,
    ind_scr_fhxplp varchar,
    ind_sur_phxcc varchar,
    ind_sur_phxplp varchar,
    ind_sur_phxplpcca varchar,
    ind_sur_fhnpcc varchar,
    ind_scr_phxcca varchar,
    ind_sur_ibd varchar,
    ibdtyp_uc varchar,
    ibdtyp_crohn varchar,
    ibdtyp_ind varchar,
    ind_diag_exam varchar,
    dex_bleed varchar,
    dex_cbh_diar varchar,
    dex_cbh_cons varchar,
    dex_cbh_diarcons varchar,
    dex_elim_ibd varchar,
    dex_biop varchar,
    dex_fobt varchar,
    dex_abn_test varchar,
    dex_abn_tst_ctc varchar,
    dex_abn_tst_bar_en varchar,
    dex_abn_tst_oth varchar,
    dex_plpect_plp varchar,
    dex_ida varchar,
    dex_oth varchar,
    find_calc_normal integer,
    find_calc_polyp integer,
    find_calc_cancer integer,
    find_calc_other integer,
    find_calc_nodata integer,
    fnd_norm_ex integer,
    fnd_plp integer,
    find_other integer,
    find_oth_bmc integer,
    find_oth_ibd integer,
    find_oth_biop integer,
    find_oth_other integer,
    wthdrwl_time varchar,
    completed integer,
    adenoma_detected_old integer,
    serrated_detected_old integer,
    constraint findings_id_pkey PRIMARY KEY (id)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE findings
  OWNER TO informatics;