create materialized view mvExport_may2018_e as select
row_number() over() as row_num,
e.event_id,
e.person_id,
a.specimen_id,
--p2_event_id,
--c_event_id,
--s_event_id,
case when a.s_event_id is not null then 'yes' else 'no' end as has_specimen,
has_colo(e.event_id) as has_colo,
case when a.p2_event_id is not null then 'yes' else 'no' end as has_polyp,
case when pr.event_id is not null then 'yes' else 'no' end as has_path,
has_survey(e.event_id) as has_survey,
case when fu.fu_event_id is not null then 'yes' else 'no' end as has_followup,
a.abort_reas_obs,
a.abort_reas_oth,
a.abort_reas_pp,
a.abort_reas_sedprob,
a.abort_reas_tc,
a.addl_polyp as addl_polyps,
sv.alcohol,
a.all_plps_rem,
pr.APC,
sv.aspirin,
sv.aspirin_duration,
pr.case_no,
a.comp_bleed,
a.comp_cardio,
a.comp_none,
a.comp_oth,
a.comp_perf,
a.comp_resparr,
pr.consult,
pr.consult_date,
a.container,
sv.coumadin,
sv.curr_ht_ft,
sv.curr_ht_in,
sv.curr_wt,
pg.degree,
a.dex_abd_pain,
a.dex_abn_test,
a.dex_abn_tst_bar_en,
a.dex_abn_tst_ctc,
a.dex_abn_tst_oth,
a.dex_biop,
a.dex_bleed,
a.dex_cbh_cons,
a.dex_cbh_diar,
a.dex_cbh_diarcons,
a.dex_elim_ibd,
a.dex_fobt,
a.dex_ida,
a.dex_oth,
a.dex_plpect_plp,
p.dob,
sv.education,
a.end_proc_stat_rr,
e.endo_barcode as barcode_endoform,
e.endo_code,
en.endo_degree,
en.endo_dob,
en.endo_fellow_discipline,
en.endo_fellow_grad_year,
en.endo_fellowship,
en.endo_gender_male,
en.endo_med_grad_year,
en.endo_specialty,
en.endo_status,
en.endo_status_date,
en.enroll_survey_done as endo_enroll_survey_done,
en.year_first_colo as endo_first_colo,
e.event_date,
e.event_type,
sv.ever_cplp,
sv.ever_cplp_fam,
sv.ever_fap,
sv.ever_hnpcc,
sv.ever_ibs,
sv.evr_crc_tab,
sv.exercise,
sv.ext_calcium,
sv.ext_calcium_daration as ext_calcium_duration,
a.f_reas_curex,
a.f_reas_famhx,
a.f_reas_ibd,
a.f_reas_oth,
a.f_reas_perhx,
f.facility_id,
f.facility_name,
a.find_oth_biop,
a.find_oth_bmc,
a.find_oth_ibd,
a.find_other,
a.find_oth_other,
a.fnd_plp,
a.fnd_norm_ex,
a.flg_assump,
a.flg_assump_numpolyps,
a.flg_dx,
a.flg_dx_multis,
a.flg_dx_site,
a.flg_dx_size,
a.flg_multis,
a.flg_multisites,
a.flg_no_discrep,
a.flg_no_path_spec,
a.flg_no_Q_spec,
a.flg_noQdata,
a.flg_num_polyps,
a.flg_path_sites,
a.flg_residual,
a.flg_review,
a.flg_site_discrep,
a.flg_site_uncert,
a.flg_size_discrep,
sv.foreign_born,
fu.fu_colo_rec,
fu.fu_docrecfut,
fu.fu_docrecscrn,
fu.fu_embarss,
fu.fu_explain,
fu.fu_feelgood,
fu.fu_lschncdy,
fu.fu_noworry,
fu.fu_nrvs,
fu.fu_pain,
fu.fu_plp_ltr,
fu.fu_plp_ltr_info,
fu.fu_plp_rem,
fu.fu_prep,
fu.fu_pstcmp_bleed,
fu.fu_pstcmp_gas,
fu.fu_pstcmp_none,
fu.fu_pstcmp_oth,
fu.fu_pstcmp_perf,
fu.fu_pstcmp_react,
fu.fu_quality,
fu.fu_scrn,
fu.fu_teleform_formid,
fu.fu_toolong,
a.fup_10,
a.fup_1t3,
a.fup_2t3,
a.fup_4t5,
a.fup_6t10,
a.fup_6t9,
a.fup_baren,
a.fup_ctc,
a.fup_gt10,
a.fup_lt1,
a.fup_nfsi,
a.fup_othproc,
a.fup_pcp,
a.fup_pp,
a.fup_rwp,
a.fup_surgcons,
p.gender_calcd,
p.source_gender_calcd,
sv.health,
a.HGD,
sv.hispanic,
a.ibd_actcol,
a.ibd_chroncol,
a.ibd_coloth,
a.ibd_ibd,
a.ibd_inactcol,
a.ibd_lgdysp,
a.ibdtyp_crohn,
a.ibdtyp_ind,
a.ibdtyp_uc,
a.ind_diag_exam,
a.ind_scr_fhxcc,
a.ind_scr_fhxcc_fdr,
a.ind_scr_fhxplp,
a.ind_scr_nosym,
a.ind_scr_phxcca,
a.ind_sur_fhnpcc,
a.ind_sur_ibd,
a.ind_sur_phxcc,
a.ind_sur_phxplp,
a.ind_sur_phxplpcca,
a.indication_calculated,
sv.ins_hmo,
sv.ins_mcaid,
sv.ins_mcare,
sv.ins_none,
sv.ins_oth,
sv.ins_priv,
sv.ins_unsure,
pl.lab_name,
sv.marital_status,
a.meds_used_demerol,
a.meds_used_fentanyl,
a.meds_used_none,
a.meds_used_other,
a.meds_used_propofol,
a.meds_used_versed,
a.n_cancer,
a.n_intra_ca,
a.n_inv_ca,
e.not_approached,
sv.nsaids,
sv.nsaids_duration,
sv.oth_fam_poly,
sv.other_ca,
sv.other_ca_fam,
a.other_dx_specify,
a.p_flat,
a.p_loc,
a.p_siz as polyp_siz,
en.participating,
a.path_polyp_loc,
pr.path_report_complete,
pg.pathologist_code,
pr.pathologist_code_cprs,
pg.Pathologist_id,
pr.pathology_date,
e.patient_barcode as barcode_pif,
sv.pcr_colon_ca,
sv.pcr_dk_tab,
sv.pcr_dvt,
sv.pcr_nofind,
sv.pcr_oth,
sv.pcr_plp,
sv.pcr_rectal_ca,
sv.pcr_roids,
a.polyp_num,
a.prep,
a.prep_typ_fleet,
a.prep_typ_halflytely,
a.prep_typ_nulytely,
a.prep_typ_osmo,
a.prep_typ_oth,
a.prep_type as colo_prep_type,
sv.prep_type as surv_prep_type,
sv.prep_type_fleet,
sv.prep_type_hal,
sv.prep_type_nul,
sv.prep_type_osmo,
sv.prep_type_oth,
sv.prev_colo,
sv.prev_sigcolo,
pr.procedure_type,
sv.pscr_bplp,
sv.pscr_cca,
sv.pscr_dvt,
sv.pscr_neg,
sv.pscr_oth,
sv.pscr_roids,
sv.psr_colon_ca,
sv.psr_dk_tab,
sv.psr_dvt,
sv.psr_never_tab,
sv.psr_nofind,
sv.psr_oth,
sv.psr_plp,
sv.psr_rectal_ca,
sv.psr_roids,
a.pt_cb,
a.pt_cs,
a.pt_hb,
a.pt_hs,
a.pt_lo,
a.pt_nr,
a.pt_o,
a.pt_pe,
a.pt_pme,
a.pt_sn,
a.pt_te,
a.Ptype_Carcinoid,
a.Ptype_Fibroblast,
a.Ptype_Ganglio,
a.Ptype_Hamart,
a.Ptype_HP,
a.Ptype_Inflam,
a.Ptype_Juvenile,
a.Ptype_Lelomyoma,
a.Ptype_Lipoma,
a.Ptype_Lymphoid,
a.Ptype_Mixed,
a.Ptype_MP,
a.Ptype_Norm_Muc,
a.Ptype_Not_Polyp,
a.Ptype_Other,
a.Ptype_PautzJeg,
a.Ptype_SA,
a.Ptype_SSP,
a.Ptype_TA,
a.Ptype_TVA,
a.Ptype_VA,
pr.Q_form_incomplete,
sv.qty_smoke,
sv.race_amind,
sv.race_asian,
sv.race_black,
sv.race_oth,
sv.race_pacisl,
sv.race_white,
a.record_complete,
p.refused,
p.refused_date,
sv.relb450_bro_pilot,
sv.relb450_dad_pilot,
sv.relb450_kid_pilot,
sv.relb450_mom_pilot,
sv.relb450_sis_pilot,
sv.relca_age_dad_tab,
sv.relca_age_mom_tab,
sv.relca_bro,
sv.relca_bro_dk_tab,
sv.relca_bro_gt60_tab,
sv.relca_dad,
sv.relca_dad_dk_tab,
sv.relca_dad_gt60_tab,
sv.relca_kid,
sv.relca_kid_dk_tab,
sv.relca_kid_gt60_tab,
sv.relca_mom,
sv.relca_mom_dk_tab,
sv.relca_mom_gt60_tab,
sv.relca_sis,
sv.relca_sis_dk_tab,
sv.relca_sis_gt60_tab,
sv.relcab450_bro as relca_bro_b450,
sv.relcab450_dad as relca_dad_b450,
sv.relcab450_dk,
sv.relcab450_kid as relca_kid_b450,
sv.relcab450_mom as relca_mom_b450,
sv.relcagt50_sis,
sv.relcab450_sis,
sv.relcagt50_bro,
sv.relcagt50_dad,
sv.relcagt50_dk,
sv.relcagt50_kid,
sv.relcagt50_mom,
pr.path_report_id,
a.site_location_cm,
a.size_mm,
sv.smoker,
a.specimen_type,
sv.state_born,
f.status,
f.status_date,
a.su_cr_loc_ac,
a.su_cr_loc_ce,
a.su_cr_loc_dc,
a.su_cr_loc_hf,
a.su_cr_loc_re,
a.su_cr_loc_sf,
a.su_cr_loc_sg,
a.su_cr_loc_tc,
a.su_cr_loc_ti,
a.su_cr_loc_u,
a.su_uc_loc_ac,
a.su_uc_loc_ce,
a.su_uc_loc_dc,
a.su_uc_loc_hf,
a.su_uc_loc_re,
a.su_uc_loc_sf,
a.su_uc_loc_sg,
a.su_uc_loc_tc,
a.su_uc_loc_ti,
a.su_uc_loc_u,
a.susp_ca as suspca,
a.susp_ca_loc as suspcaloc,
a.susp_ca_siz,
a.susp_ca_trt_cb,
a.susp_ca_trt_cs,
a.susp_ca_trt_hb,
a.susp_ca_trt_hs,
a.susp_ca_trt_lo,
a.susp_ca_trt_nr,
a.susp_ca_trt_o,
a.susp_ca_trt_pe,
a.susp_ca_trt_pme,
a.susp_ca_trt_sn,
a.susp_ca_trt_te,
a.susp_crohns,
a.susp_crohns_calced,
a.susp_UC,
a.susp_UC_calced,
a.T_class,
a.teleform_formid as formid_endoform,
sv.teleform_formid as formid_pif,
sv.vitamin_duration,
sv.vitamins,
sv.vitamins_pilot,
sv.vr_bleed,
sv.vr_crohn_age_dx,
sv.vr_dk_tab,
sv.vr_fhxcca,
sv.vr_fhxp,
sv.vr_none_tab,
sv.vr_nosymp,
sv.vr_other,
sv.vr_phx_crohn,
sv.vr_phx_uc,
sv.vr_phxcca,
sv.vr_phxp,
sv.vr_uc_age_dx,
sv.vr_uccrohn,
sv.wt_20,
a.wthdrwl_time as withdrwl_time,
sv.yrs_smoke,
f.zip
from vevents_e e
join person p ON e.person_id = p.person_id
left outer join vAll_e2 a on a.event_id = e.event_id
left outer join path_report pr ON pr.event_id = e.event_id
left outer join survey sv ON sv.event_id = e.event_id
left outer join vfollow_up fu ON e.event_id = fu.fu_event_id
left outer join endoscopist en ON e.endo_code = en.endoscopist_id
left outer join pathologist pg ON pr.pathologist_code_cprs = pg.pathologist_code
left outer join facility f ON e.facility_id = f.facility_id
left outer join path_lab pl ON pr.lab_code = pl.lab_code
where (refused = 0 or refused is null or (refused_date > event_date)) and event_date >= '2004-01-01' and e.facility_id != 'CS200' and 
	not (event_type='Colonoscopy' and a.s_event_id is null and pr.event_id is null  and (has_colo(e.event_id) = 'no' or has_colo(e.event_id) = 'empty') and 
		(has_survey(e.event_id) = 'no' or has_survey(e.event_id) = 'empty')) and 
	not (event_type = 'LINK' and pr.event_id is null)
		
		order by row_num;
