create view vColo_path as select
    action_on,
    action_by,
    colo_id,
    event_id,
    to_char(exam_date,'yyyy-mm-dd') as exam_date,
    fnd_norm_ex ,
    fnd_plp ,
    p_loc_a ,
    p_loc_b ,
    p_loc_c ,
    p_loc_d ,
    p_loc_e ,
    p_loc_f ,
    p_loc_g ,
    p_loc_h ,
    p_loc_i ,
    p_loc_j ,
    get_polyp_size(p_siz_a) as ps_a,
    get_polyp_size(p_siz_b) as ps_b,
    get_polyp_size(p_siz_c) as ps_c,
    get_polyp_size(p_siz_d) as ps_d,
    get_polyp_size(p_siz_e) as ps_e,
    get_polyp_size(p_siz_f) as ps_f,
    get_polyp_size(p_siz_g) as ps_g,
    get_polyp_tx(pt_cb_a ,pt_hb_a ,pt_hs_a ,pt_cs_a ,pt_pme_a ,pt_pe_a ,pt_nr_a ,pt_lo_a ,pt_o_a) as pt_a,
    get_polyp_tx(pt_cb_b ,pt_hb_b ,pt_hs_b ,pt_cs_b ,pt_pme_b ,pt_pe_b ,pt_nr_b ,pt_lo_b ,pt_o_b) as pt_b,
    get_polyp_tx(pt_cb_c ,pt_hb_c ,pt_hs_c ,pt_cs_c ,pt_pme_c ,pt_pe_c ,pt_nr_c ,pt_lo_c ,pt_o_c) as pt_c,
    get_polyp_tx(pt_cb_d ,pt_hb_d ,pt_hs_d ,pt_cs_d ,pt_pme_d ,pt_pe_d ,pt_nr_d ,pt_lo_d ,pt_o_d) as pt_d,
    get_polyp_tx(pt_cb_e ,pt_hb_e ,pt_hs_e ,pt_cs_e ,pt_pme_e ,pt_pe_e ,pt_nr_e ,pt_lo_e ,pt_o_e) as pt_e,
    get_polyp_tx(pt_cb_f ,pt_hb_f ,pt_hs_f ,pt_cs_f ,pt_pme_f ,pt_pe_f ,pt_nr_f ,pt_lo_f ,pt_o_f) as pt_f,
    get_polyp_tx(pt_cb_g ,pt_hb_g ,pt_hs_g ,pt_cs_g ,pt_pme_g ,pt_pe_g ,pt_nr_g ,pt_lo_g ,pt_o_g) as pt_g,
    addl_polyp ,
    all_plps_rem ,
    susp_ca ,
    susp_ca_loc ,
    get_polyp_size(susp_ca_siz) as susp_ca_siz,
    get_polyp_tx (susp_ca_trt_cb ,susp_ca_trt_hb ,susp_ca_trt_hs ,susp_ca_trt_cs ,susp_ca_trt_pme ,susp_ca_trt_pe ,susp_ca_trt_nr ,susp_ca_trt_lo ,susp_ca_trt_o) as susp_ca_tx,
    p_flat_a ,
    p_flat_b ,
    p_flat_c ,
    p_flat_d ,
    p_flat_e ,
    p_flat_f ,
    p_flat_g ,
    find_other ,
    find_oth_bmc ,
    find_oth_ibd ,
    find_oth_biop ,
    find_oth_other 
    from colo;
    grant select on vColo_path to NHCR2_rc;