create view vExport_NHCR3_2 as select
row_number() over() as row_num,
e.event_id as e_event_id,
p.person_id,
p2_event_id,
e.person_id as e_person_id,
c_event_id,
s_event_id,
a.meds_used_other,
a.meds_used_propofol,
a.meds_used_versed,
a.n_cancer,
a.N_class,
a.n_intra_ca,
a.n_inv_ca,
pr.no_Q_form,
e.not_approached,
sv.nsaids,
sv.nsaids_duration,
a.old_polyp_id,
sv.oth_fam_poly,
sv.other_ca,
sv.other_ca_fam,
a.other_dx_specify,
a.p_flat,
a.p_loc,
a.p_siz as polyp_siz,
en.participating,
pl.path_lab_id,
a.path_polyp_loc,
pr.path_report_complete,
pg.pathologist_code,
pr.pathologist_code_cprs,
pg.Pathologist_id,
pr.pathology_date,
e.patient_barcode as barcode_pif,
e.patient_form_double_entered,
sv.patient_id,
sv.pcr_colon_ca,
sv.pcr_dk_tab,
sv.pcr_dvt,
sv.pcr_nofind,
sv.pcr_oth,
sv.pcr_plp,
sv.pcr_rectal_ca,
sv.pcr_roids,
a.polyp_num,
a.prep,
a.prep_typ_fleet,
a.prep_typ_halflytely,
a.prep_typ_nulytely,
a.prep_typ_osmo,
a.prep_typ_oth,
a.prep_type as colo_prep_type,
sv.prep_type as surv_prep_type,
sv.prep_type_fleet,
sv.prep_type_hal,
sv.prep_type_nul,
sv.prep_type_osmo,
sv.prep_type_oth,
sv.prev_colo,
sv.prev_sigcolo,
pr.procedure_type,
sv.pscr_bplp,
sv.pscr_cca,
sv.pscr_dvt,
sv.pscr_neg,
sv.pscr_oth,
sv.pscr_roids,
sv.psr_colon_ca,
sv.psr_dk_tab,
sv.psr_dvt,
sv.psr_never_tab,
sv.psr_nofind,
sv.psr_oth,
sv.psr_plp,
sv.psr_rectal_ca,
sv.psr_roids,
a.pt_cb,
a.pt_cs,
a.pt_hb,
a.pt_hs,
a.pt_lo,
a.pt_nr,
a.pt_o,
a.pt_pe,
a.pt_pme,
a.pt_sn,
a.pt_te,
f.pth_req_required,
a.Ptype_Carcinoid,
a.Ptype_Fibroblast,
a.Ptype_Ganglio,
a.Ptype_Hamart,
a.Ptype_HP,
a.Ptype_Inflam,
a.Ptype_Juvenile,
a.Ptype_Lelomyoma,
a.Ptype_Lipoma,
a.Ptype_Lymphoid,
a.Ptype_Mixed,
a.Ptype_MP,
a.Ptype_Norm_Muc,
a.Ptype_Not_Polyp,
a.Ptype_Other,
a.Ptype_PautzJeg,
a.Ptype_SA,
a.Ptype_SSP,
a.Ptype_TA,
a.Ptype_TVA,
a.Ptype_VA,
pr.Q_form_incomplete,
sv.qty_smoke,
sv.race_amind,
sv.race_asian,
sv.race_black,
sv.race_oth,
sv.race_pacisl,
sv.race_white,
a.record_complete,
p.refused,
p.refused_date,
sv.relb450_bro_pilot,
sv.relb450_dad_pilot,
sv.relb450_kid_pilot,
sv.relb450_mom_pilot,
sv.relb450_sis_pilot,
sv.relca_age_dad_tab,
sv.relca_age_mom_tab,
sv.relca_bro,
sv.relca_bro_dk_tab,
sv.relca_bro_gt60_tab,
sv.relca_dad,
sv.relca_dad_dk_tab,
sv.relca_dad_gt60_tab,
sv.relca_kid,
sv.relca_kid_dk_tab,
sv.relca_kid_gt60_tab,
sv.relca_mom,
sv.relca_mom_dk_tab,
sv.relca_mom_gt60_tab,
sv.relca_sis,
sv.relca_sis_dk_tab,
sv.relca_sis_gt60_tab,
sv.relcab450_bro as relca_bro_b450,
sv.relcab450_dad as relca_dad_b450,
sv.relcab450_dk,
sv.relcab450_kid as relca_kid_b450,
sv.relcab450_mom as relca_mom_b450,
sv.relcagt50_sis,
sv.relcab450_sis,
sv.relcagt50_bro,
sv.relcagt50_dad,
sv.relcagt50_dk,
sv.relcagt50_kid,
sv.relcagt50_mom,
pr.path_report_id,
pr.serr_det_manual,
pr.serrated_detected,
p.sex_female,
p.sex_male,
a.site_location_cm,
a.size_mm,
sv.smoker,
p.source_gender_calcd,
a.specimen_type,
sv.state_born,
f.status,
f.status_date,
a.su_cr_loc_ac,
a.su_cr_loc_ce,
a.su_cr_loc_dc,
a.su_cr_loc_hf,
a.su_cr_loc_re,
a.su_cr_loc_sf,
a.su_cr_loc_sg,
a.su_cr_loc_tc,
a.su_cr_loc_ti,
a.su_cr_loc_u,
a.su_uc_loc_ac,
a.su_uc_loc_ce,
a.su_uc_loc_dc,
a.su_uc_loc_hf,
a.su_uc_loc_re,
a.su_uc_loc_sf,
a.su_uc_loc_sg,
a.su_uc_loc_tc,
a.su_uc_loc_ti,
a.su_uc_loc_u,
a.susp_ca as suspca,
a.susp_ca_loc as suspcaloc,
a.susp_ca_siz,
a.susp_ca_trt_cb,
a.susp_ca_trt_cs,
a.susp_ca_trt_hb,
a.susp_ca_trt_hs,
a.susp_ca_trt_lo,
a.susp_ca_trt_nr,
a.susp_ca_trt_o,
a.susp_ca_trt_pe,
a.susp_ca_trt_pme,
a.susp_ca_trt_sn,
a.susp_ca_trt_te,
a.susp_crohns,
a.susp_crohns_calced,
a.susp_UC,
a.susp_UC_calced,
a.T_class,
a.teleform_formid as formid_endoform,
sv.teleform_formid as formid_pif,
sv.vitamin_duration,
sv.vitamins,
sv.vitamins_pilot,
sv.vr_bleed,
sv.vr_crohn_age_dx,
sv.vr_dk_tab,
sv.vr_fhxcca,
sv.vr_fhxp,
sv.vr_none_tab,
sv.vr_nosymp,
sv.vr_other,
sv.vr_phx_crohn,
sv.vr_phx_uc,
sv.vr_phxcca,
sv.vr_phxp,
sv.vr_uc_age_dx,
sv.vr_uccrohn,
sv.wt_20,
a.wthdrwl_time as withdrwl_time,
a.y_prefix,
en.year_first_colo,
en.year_first_colo_here,
sv.yrs_smoke,
f.zip
from event e
join person p ON e.person_id = p.person_id
left outer join vAll a on a.event_id = e.event_id
left outer join path_report pr ON pr.event_id = e.event_id
left outer join survey sv ON sv.event_id = e.event_id
left outer join vfollow_up fu ON e.event_id = fu.fu_event_id
left outer join endoscopist en ON e.endo_code = en.endoscopist_id
left outer join pathologist pg ON pr.pathologist_code_cprs = pg.pathologist_code
left outer join facility f ON a.facility_id = f.facility_id
left outer join path_lab pl ON pr.lab_code = pl.lab_code
where (refused = 0 or refused is null) and event_date >= '2004-01-01'
order by row_num;
