create view vEndoscopist as select
    endoscopist_id,
    action_on,
    action_by,
    endo_initials,
    endo_first_name,
    endo_middle_name,
    endo_last_name,
    endo_name_suffix,
    endo_degree,
    salutation,
    mail_name,
    endo_organization,
    endo_address1,
    endo_address2,
    endo_address3,
    endo_city,
    endo_state,
    endo_zip ,
    endo_direct_phone,
    endo_pager,
    endo_other_phone,
    endo_email,
    to_char(endo_dob,'yyyy-mm-dd') as endo_dob,
    endo_gender_male ,
    endo_specialty,
    endo_med_grad_year ,
    endo_fellowship ,
    endo_fellow_grad_year ,
    endo_fellow_discipline,
    year_first_colo ,
    comments,
    participating ,
    main_site,
    report_handling ,
    enroll_survey_done ,
    steering_committee ,
    endo_status,
    to_char(endo_status_date,'yyyy-mm-dd') as endo_status_date,
    endo_pseudo_name 
    from endoscopist order by endo_last_name;
grant select on vEndoscopist to NHCR2_rc;