create view vFacilities as select
    facility_id ,
    action_on,
    action_by,
    record_comment ,
    to_char(inserted_on,'yyyy-mm-dd') as inserted_on,
    inserted_by ,
    facility_name ,
    facility_pseudo_name ,
    address1 ,
    address2 ,
    address3 ,
    city ,
    state ,
    zip ,
    fax ,
    status ,
    to_char(status_date,'yyyy-mm-dd') as status_date,
    to_char(implementation_date,'yyyy-mm-dd') as implementation_date,
    facility_type ,
    how_write_reports ,
    comments ,
    contact1_name ,
    contact1_phone ,
    contact1_email ,
    contact1_type ,
    contact2_name ,
    contact2_phone ,
    contact2_email ,
    contact2_type ,
    contact3_name ,
    contact3_phone ,
    contact3_email ,
    contact3_type ,
    pth_reports_contact_name ,
    pth_reports_contact_phone ,
    pth_reports_contact_email ,
    pth_req_required,
    pth_consent_form_reqd,
    pth_req_sort_col ,
    pth_req_instructions,
    irb_of_record ,
    to_char(irb_review_date,'yyyy-mm-dd') as irb_review_date,
    irb_consent_form ,
    irb_active_consent_version ,
    to_char(irb_approval_date,'yyyy-mm-dd') as irb_approval_date,
    to_char(irb_expiration_date,'yyyy-mm-dd') as irb_expiration_date,
    irb_contact_name ,
    irb_contact_phone ,
    irb_contact_email 
    from
        facility order by facility_name;
grant select on vFacilities to NHCR2_rc;