create view vPathReport as select
    path_report_id,
    action_on,
    action_by,
    inserted_on,
    inserted_by,
    event_id ,
    path_report_complete,
    patient_ID ,
    to_char(date_of_birth,'yyyy-mm-dd') as date_of_birth,
    gender,
    case_no,
    procedure_type,
    consult,
    to_char(consult_date,'yyyy-mm-dd') as consult_date,
    endoscopist_id_cprs ,
    amended_path_report,
    pathologist_code_cprs,
    to_char(pathology_date,'yyyy-mm-dd') as pathology_date,
    lab_code,
    no_Q_form,
    Q_form_incomplete,
    apc,
    SAS_import_notes,
    pseudo_patient_id,
    source,
    study_site,
    rec_type,
    Notes,
    sas_key_id ,
    pth_req_id ,
    adenoma_detected,
    ad_det_manual,
    px_gender_male,
    px_gender_female,
    serrated_detected,
    serr_det_manual,
    gender_calcd,
    crohns_only,
    u_colitis_only,
    date_discrepancy
    from path_report;

GRANT select on vPathReport to nhcr2_rc;