create view vPathReport as select
    path_report_id,
    p.action_on,
    p.action_by,
    p.inserted_on,
    p.inserted_by,
    p.event_id ,
    path_report_complete,
    p.person_id ,
    to_char(date_of_birth,'yyyy-mm-dd') as dob,
    gender,
    case_no,
    procedure_type,
    consult,
    to_char(consult_date,'yyyy-mm-dd') as consult_date,
    endoscopist_id ,
    amended_path_report,
    pathologist_code_cprs,
    to_char(pathology_date,'yyyy-mm-dd') as pathology_date,
    lab_code,
    no_Q_form,
    Q_form_incomplete,
    apc,
    SAS_import_notes,
    pseudo_patient_id,
    source,
    study_site,
    rec_type,
    Notes,
    sas_key_id ,
    pth_req_id ,
    adenoma_detected,
    ad_det_manual,
    px_gender_male,
    px_gender_female,
    serrated_detected,
    serr_det_manual,
    gender_calcd,
    crohns_only,
    u_colitis_only,
    date_discrepancy,
    b.facility_id,
    e.endo_barcode
    from path_report p join event e on p.event_id = e.event_id join batch b on e.batch_id = b.batch_id;

GRANT select on vPathReport to nhcr2_rc;