create view vPolypSpecimen_e as 
select
	case 
		when (s.event_id is not null) then s.event_id 
		when (p2.c_event_id is not null) then p2.c_event_id end as event_id,
    c_event_id,
    p2_event_id,
    s.event_id as s_event_id,
    old_polyp_id,
    p_loc ,
    p_siz ,
    pt_cb ,
    pt_hb ,
    pt_hs ,
    pt_cs ,
    pt_pme ,
    pt_pe ,
    pt_nr ,
    pt_lo ,
    pt_o ,
    pt_sn ,
    pt_te ,
    p2.notes as p2_notes,
    p_flat,
    specimen_id,
    path_report_id ,
    path_polyp_loc,
    polyp_num,
    discrepnote,
    container,
    fragment,
    other_dx_specify,
    site_location_cm ,
    site_desc,
    size_mm ,
    anallevel ,
    flg_no_path_spec ,
    ptype_carcinoid ,
    ptype_ganglio ,
    ptype_hamart ,
    ptype_hp ,
    ptype_inflam ,
    ptype_juvenile ,
    ptype_lelomyoma ,
    ptype_lipoma ,
    ptype_mp ,
    ptype_norm_muc ,
    ptype_not_polyp ,
    ptype_other ,
    ptype_pautzjeg ,
    ptype_sa ,
    ptype_ssp ,
    ptype_mixed ,
    ptype_ta ,
    ptype_tva ,
    ptype_va ,
    flg_dx ,
    flg_no_discrep ,
    flg_no_q_spec ,
    flg_num_polyps ,
    flg_site_discrep ,
    flg_site_uncert ,
    flg_path_sites ,
    flg_review ,
    hgd ,
    ibd_ibd ,
    ibd_actcol ,
    ibd_chroncol ,
    ibd_coloth ,
    ibd_inactcol ,
    ibd_lgdysp ,
    n_intra_ca ,
    n_inv_ca ,
    n_cancer ,
    ptype_fibroblast ,
    ptype_lymphoid ,
    flg_noqdata ,
    flg_assump ,
    flg_multis ,
    flg_multisites ,
    flg_residual ,
    flg_assump_numpolyps ,
    flg_dx_size ,
    flg_dx_site ,
    flg_dx_multis ,
    specimen_type,
    s.notes as s_notes,
    t_class,
    n_class,
    date_of_export,
    y_prefix ,
    record_complete ,
    flg_size_discrep ,
    sas_key_id from
    vpolyp2C_e p2
    full join vspecimen s ON 
        s.event_id = c_event_id AND 
        s.specimen_type::text = 'Polyp'::text 
        AND s.polyp_num::text = p2.old_polyp_id::text;